### ISSUE TITLE
Argocd refuses to deploy the Helm resources due to missing namespace

### ISSUE THREAD

**Issue by cmoulliard** [quarkiverse/quarkus-argocd#36]
## Issue

Argocd refuses to deploy the Helm resources due to missing namespace not defined for the Deployment, Service

![Screenshot 2024-09-24 at 13 53 42](https://github.com/user-attachments/assets/626e5159-7285-4ca5-b6d6-8b1408e6c1b9)

@iocanel

**Comment by iocanel** [comment]
The install command does provide flags for setting the namespace.
This is also possibly via application.properties

What we need to do, is have the install command fail if no namespace is specified.

**Comment by cmoulliard** [comment]
Issue fixed as `namespaces` parameters are available to configure the `Application` or `AppProject` generated
